### PR TITLE
update to latest clojure & clojure-csv

### PR DESCRIPTION
**Pull request by cap10morgan**
This eliminated the need for the reversing in core/parse-csv.

### CODE REVIEW

**Comment by cap10morgan** [comment]
ping

**Comment by cap10morgan** [comment]
Should I close this? Is this still maintained?

**Comment by cap10morgan** [comment]
I guess this is no longer maintained.

**Comment by WhittlesJr** [comment]
@cap10morgan , I need these changes as well, and I have one other minor improvement I'd like to see in the `keyordize-` function. Do you think you would like to publish your own fork to clojars?

**Comment by cap10morgan** [comment]
@WhittlesJr I'm not using it much these days. You might want to publish your own fork with my or whatever other changes you'd like to have in there. I wouldn't want to add yet another unmaintained lib. :)

**Pull request closed without merging**
